VShuttle/Controllers/LoginController.cs
using System;
using System.DirectoryServices.AccountManagement;
using System.Web.Mvc;
using VShuttle.Model;
using System.Configuration;



namespace VShuttle.Controllers
{
    public class LoginController : Controller
    {

        // GET: Admin
        public ActionResult Index()
        {
            if (Session["Id"] != null)
                return RedirectToAction("Index", "Home");
            return View();
        }
     
        [HttpPost]
        public ActionResult Index(Users users)
        {
           
            PrincipalContext ctx = new PrincipalContext(ContextType.Domain);
            bool isValid = ctx.ValidateCredentials(users.INumber, users.Password);
            UserPrincipal user = UserPrincipal.FindByIdentity(ctx, users.INumber);
            var admin = ConfigurationManager.AppSettings["AdminINumber"];
            if (isValid)
            {               
                string INumber = users.INumber;
                Session["Id"] = INumber;
                Session["UserName"] = user.Name;
                if(INumber == admin) 
                    Session["UserRole"] = 1;
                else
                    Session["UserRole"] = 2;
                if(Convert.ToInt32(Session["UserRole"]) == 1)
                    return RedirectToAction("Index", "Home");
                 return RedirectToAction("Index", "Home");
            }
            ViewData["error"] = "Invalid username or password !!!";
            return View();
        }

    }
}

VShuttle/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VShuttle.Controllers
{
    public class LogoutController : Controller
    {
        // GET: Logout
        public ActionResult Index()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

VShuttle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vshuttle</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Verscend shuttle</a>
            </div>

                    
            <div class="navbar-header right-header pull-right">
                @if (Session["Id"] != null)
                {
                    <i class="navbar-brand headerlogin">Welcome, @Session["UserName"]</i>
                    <a class="navbar-brand headerlogin" href="@Url.Action("Index","Logout")">Logout</a>
                }
                else
                {
                   <a class="navbar-brand headerlogin" href="@Url.Action("Index","Login")">Login</a>
                }
               
            </div>

        </div>
    </nav>
    
    <div class="container-fluid">
       
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")    
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/ajaxGrid")
        @Scripts.Render("~/bundles/Shared")
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDq0QcBfmGJaAq5Lu1Ik57BxqRKyY93_jw&libraries=places&language=en"  type="text/javascript"></script>     
        @Html.Partial("~/Views/Shared/_confirmationMessage.cshtml")            
        @RenderBody()
        
    </div>
   @RenderSection("scripts", required: false)
   @Scripts.Render("~/bundles/mapcomponents")
   @Scripts.Render("~/bundles/Timeline")
</body>
</html>

VShuttle/Views/Shared/_confirmationMessage.cshtml
@if (Session["Status"] != null)
{
    if (Convert.ToString(Session["Status"]) == "Failed")
    {
        <div class="alert alert-danger alert-dismissible" role="alert" style="margin-top:10px;" >
            <button type='button' class='close' data-dismiss='alert' aria-label=''><span aria-hidden='true' style='color: red;'> x </span></button>
            <span style="display: inline-block; position: relative; top: 0px;"><img src="~/Content/Image/error.png" /></span>
            <span>@Convert.ToString(Session["Message"])</span>
        </div>
    }
    else
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type='button' class='close' data-dismiss='alert' aria-label=''><span aria-hidden='true' style='color:green;'> x </span></button>
            <span style="display: inline-block; position: relative; top: 0px;"><img src="~/Content/Image/success.png" /></span>
            <span style="display: inline-block">@Convert.ToString(Session["Message"])</span>
        </div>

    }

    Session["Status"] = null;
    Session["Message"] = null;
}
